import { defineField, defineType } from "sanity";
import { generateRichtextField } from "../blocks/defaultFields";
export default defineType({
  name: "site_settings",
  title: "Site Settings",
  type: "document",
  groups: [
    { name: "general", title: "General", default: true },
    { name: "announcement", title: "Announcement Bar" },
    { name: "footer", title: "Footer" },
    { name: "social", title: "Social" },
    { name: "seo", title: "SEO" },
    { name: "legal", title: "Legal" },
    { name: "integrations", title: "Integrations" },
  ],
  fields: [
    defineField({
      name: "logo",
      title: "Logo",
      type: "image",
      group: "general",
    }),
    defineField({
      name: "og_image",
      title: "Open Graph Image (Site-wide)",
      description:
        "Used for social sharing previews. Set page-specific images in Page documents.",
      type: "image",
      group: "general",
    }),
    defineField({
      name: "enable_dark_mode",
      title: "Enable Dark Mode",
      description: "Show a dark/light mode toggle in the footer.",
      type: "boolean",
      initialValue: false,
      group: "general",
    }),
    defineField({
      name: "header_variant",
      title: "Header Variant",
      type: "string",
      group: "general",
      initialValue: "variant02",
      options: {
        list: [
          { title: "HeaderVariant01 - Basic", value: "variant01_basic" },
          { title: "HeaderVariant01 - Glass", value: "variant01_glass" },
          { title: "HeaderVariant02", value: "variant02" },
        ],
      },
    }),
    defineField({
      name: "header_button_title",
      title: "Header Button Title",
      type: "string",
      initialValue: `Get Strted`,
      group: "general",
    }),
    defineField({
      name: "header_button_destination",
      title: "Header Button Destination",
      type: "string",
      group: "general",
    }),
    defineField({
      name: "header_click_to_call_title",
      title: "Header Click To Call Title",
      type: "string",
      group: "general",
    }),
    defineField({
      name: "header_click_to_call_destination",
      title: "Header Click To Call Destination",
      type: "string",
      group: "general",
    }),
    defineField({
      name: "announcement_bar_enabled",
      title: "Enable Announcement Bar",
      description: "Show the announcement bar above the header.",
      type: "boolean",
      initialValue: false,
      group: "announcement",
    }),
    defineField({
      name: "announcement_bar_title",
      title: "Title",
      description: "Main message shown in the announcement bar.",
      type: "string",
      group: "announcement",
    }),
    defineField({
      name: "announcement_bar_button_title",
      title: "Button Title",
      type: "string",
      group: "announcement",
    }),
    defineField({
      name: "announcement_bar_button_url",
      title: "Button URL",
      type: "string",
      group: "announcement",
    }),
    defineField({
      name: "announcement_bar_theme",
      title: "Theme",
      type: "string",
      group: "announcement",
      initialValue: "primary",
      options: {
        list: [
          { title: "Primary (Branding Color)", value: "primary" },
          { title: "Secondary (Branding Color)", value: "secondary" },
        ],
      },
    }),
    defineField({
      name: "announcement_bar_pattern",
      title: "Background Pattern",
      type: "string",
      group: "announcement",
      initialValue: "grid",
      options: {
        list: [
          { title: "None", value: "none" },
          { title: "Grid (Boxes)", value: "grid" },
          { title: "Diagonal Stripes", value: "diagonal" },
          { title: "Diamonds", value: "diamonds" },
        ],
      },
    }),
    defineField({
      name: "announcement_bar_custom_bg",
      title: "Custom Background",
      description:
        "Overrides the theme color. Accepts any CSS background value — solid color (e.g. #1a1a2e), gradient (e.g. linear-gradient(90deg, #e52d27, #b31217)), etc.",
      type: "string",
      group: "announcement",
    }),
    defineField({
      name: "announcement_bar_enable_phone_svg",
      title: "Enable Phone Icon",
      description: "Show a phone icon on the left side of the announcement bar.",
      type: "boolean",
      initialValue: false,
      group: "announcement",
    }),
    defineField({
      name: "footer_description",
      title: "Footer Description",
      type: "text",
      group: "footer",
      rows: 3,
    }),
    defineField({
      name: "footer_quick_menu_title",
      title: "Footer Quick Menu Title",
      type: "string",
      group: "footer",
      initialValue: `Quick Menu`,
    }),
    defineField({
      name: "footer_contact_title",
      title: "Footer Contact Title",
      type: "string",
      group: "footer",
      initialValue: `Get in Touch`,
    }),
    generateRichtextField({
      name: "footer_contact_richtext",
      title: "Footer Contact Richtext",
      group: "footer",
      initialValue: [],
    }),
    defineField({
      name: "instagram_url",
      title: "Instagram URL",
      type: "string",
      group: "social",
    }),
    defineField({
      name: "facebook_url",
      title: "Facebook URL",
      type: "string",
      group: "social",
    }),
    defineField({
      name: "x_url",
      title: "X URL",
      type: "string",
      group: "social",
    }),
    defineField({
      name: "linkedin_url",
      title: "LinkedIn URL",
      type: "string",
      group: "social",
    }),
    defineField({
      name: "youtube_url",
      title: "Youtube URL",
      type: "string",
      group: "social",
    }),
    defineField({
      name: "gtm_id",
      title: "Google Tag Manager ID",
      description: "e.g. GTM-XXXXXXX. Leave blank to disable GTM.",
      type: "string",
      group: "integrations",
    }),
    defineField({
      name: "enable_top_loader",
      title: "Enable Top Loader",
      description: "Show a progress bar at the top of the page on route changes.",
      type: "boolean",
      initialValue: false,
      group: "general",
    }),
    defineField({
      name: "disable_indexing",
      title: "Disable Site Indexing",
      description:
        "⚠️ Warning: When enabled, this instructs all search engines to not index any page on this website. Use only for staging/private sites.",
      type: "boolean",
      initialValue: false,
      group: "seo",
    }),
    defineField({
      name: "privacy_policy_url",
      title: "Privacy Policy URL",
      type: "string",
      group: "legal",
    }),
    defineField({
      name: "terms_url",
      title: "Terms URL",
      type: "string",
      group: "legal",
    }),
  ],
  preview: {
    prepare: () => ({
      title: "Site settings",
    }),
  },
});
